### ISSUE TITLE
InputWeight

### ISSUE THREAD

**Issue by philbuendia** [udacity/project-pixel-art-maker-starter#13]
I just wanted to bring to your attention that there seem to be a typo on the html file. The inputWeight ID should be inputWidth.

Thanks!

**Comment by lailys** [comment]
Thanks Philip,I saw your message just now.
I wrote the code with " inputWidth" and it was not working and I could not find any logic why:D Matt on slack mentioned it and now the code works . 

Again thank you:) I totally missed your hint!
